// Sources/Persistence/Repositories/EntitlementRepository.swift
// WealthLedger — Entitlement Repository for MySQL entitlements Table
//
// Provides CRUD operations for the entitlements table and domain-specific
// permission flag queries by userId + accountGroupId combination. This is the
// persistence foundation for Rule 4 (Entitlement Enforcement).
//
// Rule 4: All data reads verify user-group entitlement before returning records.
//         Users without READ access get empty result set — not an error.
// Rule 7: Batch memory cap — findAll pagination capped at 1,000.
// Rule 8: MySQLKit-only persistence — NO SwiftData.
// Rule 10: Schema referential integrity — entitlements has FKs to users and account_groups.

import Foundation
import MySQLKit
import MySQLNIO
import SQLKit
import NIOCore
import Logging
import Shared

// MARK: - Entitlement Model

/// Represents a per-user per-account-group permission assignment in the WealthLedger RBAC system.
///
/// Maps directly to the MySQL `entitlements` table (003_create_entitlements.sql).
/// This struct is defined in the Persistence module to enable `EntitlementRepository`
/// to implement `RepositoryProtocol` with concrete type binding, since the
/// Persistence module cannot import RBAC (which would create a circular
/// dependency: RBAC → Persistence → RBAC).
///
/// ## Column Mapping
/// - `id`              → `BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY`
/// - `userId`          → `user_id BIGINT UNSIGNED NOT NULL` (FK → `users.id`)
/// - `accountGroupId`  → `account_group_id BIGINT UNSIGNED NOT NULL` (FK → `account_groups.id`)
/// - `canRead`         → `can_read BOOLEAN NOT NULL DEFAULT FALSE`
/// - `canCreate`       → `can_create BOOLEAN NOT NULL DEFAULT FALSE`
/// - `canModify`       → `can_modify BOOLEAN NOT NULL DEFAULT FALSE`
/// - `canDelete`       → `can_delete BOOLEAN NOT NULL DEFAULT FALSE`
///
/// ## Rule 4 (Entitlement Enforcement)
/// When `canRead` is `false`, queries for the associated account group return an
/// empty result set for this user — never an error.
public struct Entitlement: Sendable, Equatable, Hashable, Codable {

    // MARK: - Properties

    /// Unique entitlement identifier, auto-generated by MySQL via AUTO_INCREMENT.
    /// Defaults to 0 for new entitlements not yet persisted.
    public let id: UInt64

    /// Foreign key referencing the user who holds this entitlement.
    /// References `users.id` via `fk_entitlements_user` constraint.
    public let userId: UInt64

    /// Foreign key referencing the account group this entitlement applies to.
    /// References `account_groups.id` via `fk_entitlements_account_group` constraint.
    public let accountGroupId: UInt64

    /// READ permission flag for the associated account group.
    /// When `false`, the user receives empty result sets for this group (Rule 4).
    public let canRead: Bool

    /// CREATE permission flag for the associated account group.
    public let canCreate: Bool

    /// MODIFY permission flag for the associated account group.
    public let canModify: Bool

    /// DELETE permission flag for the associated account group.
    public let canDelete: Bool

    // MARK: - Initializer

    /// Creates a new `Entitlement` instance.
    ///
    /// - Parameters:
    ///   - id: The unique entitlement identifier. Defaults to `0` for new entitlements
    ///         that have not yet been persisted (MySQL assigns the actual ID via
    ///         AUTO_INCREMENT on insert).
    ///   - userId: The foreign key referencing the user who holds this entitlement.
    ///             Must correspond to an existing user record.
    ///   - accountGroupId: The foreign key referencing the account group this
    ///                     entitlement applies to. Must correspond to an existing
    ///                     account group record.
    ///   - canRead: READ permission flag. When `false`, queries for this group
    ///              return empty results for this user (Rule 4).
    ///   - canCreate: CREATE permission flag for the associated account group.
    ///   - canModify: MODIFY permission flag for the associated account group.
    ///   - canDelete: DELETE permission flag for the associated account group.
    public init(
        id: UInt64 = 0,
        userId: UInt64,
        accountGroupId: UInt64,
        canRead: Bool,
        canCreate: Bool,
        canModify: Bool,
        canDelete: Bool
    ) {
        self.id = id
        self.userId = userId
        self.accountGroupId = accountGroupId
        self.canRead = canRead
        self.canCreate = canCreate
        self.canModify = canModify
        self.canDelete = canDelete
    }

    // MARK: - Convenience Methods

    /// Checks whether this entitlement grants a specific permission by name.
    ///
    /// Maps human-readable permission strings to the corresponding boolean flag.
    /// The comparison is case-insensitive to support flexible usage from service
    /// layers and UI components.
    ///
    /// Used by `EntitlementService.checkPermission(userId:accountGroupId:permission:)`
    /// to efficiently evaluate a specific permission by name.
    ///
    /// - Parameter permission: The permission name to check. Recognized values
    ///   are `"READ"`, `"CREATE"`, `"MODIFY"`, and `"DELETE"` (case-insensitive).
    /// - Returns: `true` if the permission is granted, `false` if the permission
    ///   is denied or the permission name is not recognized.
    public func hasPermission(_ permission: String) -> Bool {
        switch permission.uppercased() {
        case "READ":
            return canRead
        case "CREATE":
            return canCreate
        case "MODIFY":
            return canModify
        case "DELETE":
            return canDelete
        default:
            return false
        }
    }
}

// MARK: - EntitlementRepositoryProtocol

/// Protocol defining the domain-specific methods that ``EntitlementService``
/// requires from an entitlement data access layer.
///
/// This protocol enables dependency injection and testability: production code
/// uses ``EntitlementRepository`` (backed by MySQL), while unit tests inject
/// lightweight mock implementations with zero database connections.
///
/// Inherits ``Sendable`` to satisfy Swift 6 strict concurrency requirements
/// when stored as `any EntitlementRepositoryProtocol` in a `Sendable` class.
public protocol EntitlementRepositoryProtocol: Sendable {

    /// Finds an entitlement by user ID and account group ID.
    /// Returns `nil` if no entitlement exists for the pair.
    func findByUserAndGroup(userId: UInt64, accountGroupId: UInt64) async throws -> Entitlement?

    /// Finds all entitlements for a given user ID.
    func findByUserId(_ userId: UInt64) async throws -> [Entitlement]

    /// Finds all entitlements for a given account group ID.
    func findByAccountGroupId(_ accountGroupId: UInt64) async throws -> [Entitlement]

    /// Creates a new entitlement in the data store.
    func create(_ entity: Entitlement) async throws -> Entitlement

    /// Updates the permission flags for an existing entitlement.
    func updatePermissions(id: UInt64, canRead: Bool, canCreate: Bool, canModify: Bool, canDelete: Bool) async throws

    /// Deletes an entitlement by user ID and account group ID combination.
    func deleteByUserAndGroup(userId: UInt64, accountGroupId: UInt64) async throws
}

// MARK: - EntitlementRepository

/// Repository for the `entitlements` table providing complete CRUD operations,
/// permission flag queries by userId + accountGroupId combination, and bulk
/// queries by userId or accountGroupId.
///
/// Conforms to `RepositoryProtocol` with `Entitlement` as Entity and `UInt64`
/// as EntityID.
///
/// ## Thread Safety (Gate 2 — Swift 6 Strict Concurrency)
/// All stored properties are immutable (`let`). `ConnectionPool` is an actor
/// (inherently `Sendable`). `Logger` from swift-log is `Sendable`. The class is
/// declared as `final class ... Sendable` without `@unchecked` since all invariants
/// are satisfied by construction.
///
/// ## Rule 4 — Entitlement Enforcement
/// `findByUserAndGroup` is the primary query for permission checks. When no
/// entitlement exists for a user-group pair, `nil` is returned — the service
/// layer interprets this as zero access and returns empty results (not errors).
///
/// ## Rule 7 — Batch Memory Cap
/// `findAll` enforces a maximum page size of `AppConstants.defaultPagination` (1,000).
///
/// ## Rule 8 — MySQLKit-Only Persistence
/// All database operations use MySQLKit/MySQLNIO exclusively. No SwiftData.
///
/// ## Rule 10 — Schema Referential Integrity
/// The `entitlements` table has FKs to `users.id` and `account_groups.id`.
/// Deletions of referenced users or groups will fail with FK constraint errors
/// if entitlements still reference them.
public final class EntitlementRepository: RepositoryProtocol, EntitlementRepositoryProtocol, Sendable {

    public typealias Entity = Entitlement
    public typealias EntityID = UInt64

    /// AsyncKit-based MySQL connection pool injected via dependency injection.
    private let pool: ConnectionPool

    /// Structured logger for repository operations.
    private let logger: Logger

    /// Creates a new EntitlementRepository with the given connection pool.
    ///
    /// - Parameters:
    ///   - pool: The connection pool for database operations.
    ///   - logger: Structured logger. Defaults to label "persistence.entitlement-repository".
    public init(
        pool: ConnectionPool,
        logger: Logger = Logger(label: "persistence.entitlement-repository")
    ) {
        self.pool = pool
        self.logger = logger
    }

    // MARK: - RepositoryProtocol Conformance

    /// Retrieves an entitlement by primary key.
    ///
    /// Executes a parameterized `SELECT` on the `entitlements` table filtering
    /// by the auto-increment primary key.
    ///
    /// - Parameter id: The entitlement's unique identifier (BIGINT UNSIGNED).
    /// - Returns: The matching `Entitlement`, or `nil` if no entitlement exists
    ///            with that ID.
    public func findById(_ id: UInt64) async throws -> Entitlement? {
        let logger = self.logger
        return try await pool.withConnection { db in
            logger.info("Finding entitlement by id: \(id)")
            let rows = try await db.query(
                "SELECT id, user_id, account_group_id, can_read, can_create, can_modify, can_delete FROM entitlements WHERE id = ?",
                [MySQLData(int: Int(id))]
            ).get()
            guard let row = rows.first else {
                return nil
            }
            return try EntitlementRepository.mapRow(row)
        }
    }

    /// Retrieves a paginated list of entitlements ordered by ID ascending.
    ///
    /// Enforces Rule 7: page size is capped at `AppConstants.defaultPagination`
    /// (1,000). Pages are 1-based; page values less than 1 are clamped to 1.
    ///
    /// - Parameters:
    ///   - page: 1-based page number. Values < 1 are clamped to 1.
    ///   - pageSize: Maximum records per page. Values > 1,000 are clamped to 1,000.
    ///               Values < 1 are clamped to 1.
    /// - Returns: Array of entitlements for the requested page, may be empty.
    public func findAll(page: Int, pageSize: Int) async throws -> [Entitlement] {
        let effectivePageSize = min(max(pageSize, 1), AppConstants.defaultPagination)
        let effectivePage = max(page, 1)
        let offset = (effectivePage - 1) * effectivePageSize
        let logger = self.logger

        return try await pool.withConnection { db in
            logger.info("Finding all entitlements: page=\(effectivePage), pageSize=\(effectivePageSize), offset=\(offset)")
            let rows = try await db.query(
                "SELECT id, user_id, account_group_id, can_read, can_create, can_modify, can_delete FROM entitlements ORDER BY id ASC LIMIT ? OFFSET ?",
                [MySQLData(int: effectivePageSize), MySQLData(int: offset)]
            ).get()
            return try rows.map { try EntitlementRepository.mapRow($0) }
        }
    }

    /// Creates a new entitlement in the database.
    ///
    /// Inserts a row into the `entitlements` table with the provided userId,
    /// accountGroupId, and four permission flags. The auto-generated ID is
    /// retrieved via `LAST_INSERT_ID()` on the same connection to guarantee
    /// correctness.
    ///
    /// ## FK Constraint Handling
    /// If `userId` does not reference an existing `users.id` or `accountGroupId`
    /// does not reference an existing `account_groups.id`, MySQL will raise an
    /// FK constraint violation error which propagates as a MySQLError.
    ///
    /// - Parameter entity: The entitlement to create. The `id` field is ignored;
    ///                     MySQL generates the auto-increment ID.
    /// - Returns: The created entitlement with the auto-generated ID populated.
    /// - Throws: MySQL FK constraint error if userId or accountGroupId don't exist.
    ///           `AppError.migrationFailed` if LAST_INSERT_ID retrieval fails.
    public func create(_ entity: Entitlement) async throws -> Entitlement {
        let userId = entity.userId
        let accountGroupId = entity.accountGroupId
        let canRead = entity.canRead
        let canCreate = entity.canCreate
        let canModify = entity.canModify
        let canDelete = entity.canDelete
        let logger = self.logger

        return try await pool.withConnection { db in
            logger.info("Creating entitlement for userId: \(userId), accountGroupId: \(accountGroupId)")

            _ = try await db.query(
                "INSERT INTO entitlements (user_id, account_group_id, can_read, can_create, can_modify, can_delete) VALUES (?, ?, ?, ?, ?, ?)",
                [
                    MySQLData(int: Int(userId)),
                    MySQLData(int: Int(accountGroupId)),
                    MySQLData(bool: canRead),
                    MySQLData(bool: canCreate),
                    MySQLData(bool: canModify),
                    MySQLData(bool: canDelete)
                ]
            ).get()

            // Retrieve the auto-generated ID on the same connection
            let idRows = try await db.query(
                "SELECT LAST_INSERT_ID() AS insert_id"
            ).get()
            guard let insertId = idRows.first?.column("insert_id")?.uint64 else {
                logger.error("Failed to retrieve LAST_INSERT_ID after entitlement creation for userId: \(userId), accountGroupId: \(accountGroupId)")
                throw AppError.dataAccessFailed("LAST_INSERT_ID returned nil after entitlement creation for userId: \(userId), accountGroupId: \(accountGroupId)")
            }

            logger.info("Created entitlement with id: \(insertId) for userId: \(userId), accountGroupId: \(accountGroupId)")
            return Entitlement(
                id: insertId,
                userId: userId,
                accountGroupId: accountGroupId,
                canRead: canRead,
                canCreate: canCreate,
                canModify: canModify,
                canDelete: canDelete
            )
        }
    }

    /// Deletes an entitlement by primary key.
    ///
    /// Removes the entitlement row matching the specified ID. If no row exists
    /// with the given ID, the operation completes silently (DELETE WHERE with no
    /// matching rows is a no-op in MySQL).
    ///
    /// - Parameter id: The entitlement's unique identifier.
    public func delete(_ id: UInt64) async throws {
        let logger = self.logger
        try await pool.withConnection { db in
            logger.info("Deleting entitlement with id: \(id)")
            _ = try await db.query(
                "DELETE FROM entitlements WHERE id = ?",
                [MySQLData(int: Int(id))]
            ).get()
            logger.info("Deleted entitlement with id: \(id)")
        }
    }

    // MARK: - Domain-Specific Methods (Rule 4 Support)

    /// Finds an entitlement by user ID and account group ID — the primary
    /// permission lookup method.
    ///
    /// This is the core query for Rule 4 (Entitlement Enforcement). Used by
    /// `EntitlementService.checkPermission()` to determine if a user has specific
    /// access to an account group. When `nil` is returned, the service layer
    /// interprets this as zero access and returns empty results (not errors).
    ///
    /// - Parameters:
    ///   - userId: The user's unique identifier.
    ///   - accountGroupId: The account group's unique identifier.
    /// - Returns: The matching `Entitlement`, or `nil` if no entitlement exists
    ///            (which means the user has no access to the group).
    public func findByUserAndGroup(userId: UInt64, accountGroupId: UInt64) async throws -> Entitlement? {
        let logger = self.logger
        return try await pool.withConnection { db in
            logger.info("Finding entitlement for userId: \(userId), accountGroupId: \(accountGroupId)")
            let rows = try await db.query(
                "SELECT id, user_id, account_group_id, can_read, can_create, can_modify, can_delete FROM entitlements WHERE user_id = ? AND account_group_id = ?",
                [MySQLData(int: Int(userId)), MySQLData(int: Int(accountGroupId))]
            ).get()
            guard let row = rows.first else {
                logger.info("No entitlement found for userId: \(userId), accountGroupId: \(accountGroupId)")
                return nil
            }
            return try EntitlementRepository.mapRow(row)
        }
    }

    /// Finds entitlements for a given user ID.
    ///
    /// Used by `EntitlementService.filterAccessibleGroups()` to determine which
    /// account groups a user can access. Returns all entitlements regardless of
    /// permission flag values — the service layer interprets which flags are active.
    ///
    /// Results are ordered by `account_group_id` ascending for deterministic output
    /// and capped at ``AppConstants/defaultPagination`` (1,000) records as a
    /// defensive guard (Rule 7 — Batch Memory Cap).
    ///
    /// - Parameter userId: The user's unique identifier.
    /// - Returns: Array of entitlements for the user, ordered by account group ID.
    ///            Returns empty array if the user has no entitlements.
    public func findByUserId(_ userId: UInt64) async throws -> [Entitlement] {
        let logger = self.logger
        let limit = AppConstants.defaultPagination
        return try await pool.withConnection { db in
            logger.info("Finding entitlements for userId: \(userId) (limit \(limit))")
            let rows = try await db.query(
                "SELECT id, user_id, account_group_id, can_read, can_create, can_modify, can_delete FROM entitlements WHERE user_id = ? ORDER BY account_group_id ASC LIMIT ?",
                [MySQLData(int: Int(userId)), MySQLData(int: limit)]
            ).get()
            logger.info("Found \(rows.count) entitlement(s) for userId: \(userId)")
            return try rows.map { try EntitlementRepository.mapRow($0) }
        }
    }

    /// Finds entitlements for a given account group ID.
    ///
    /// Returns user entitlements associated with the specified account group.
    /// Useful for admin views showing which users have access to a particular group
    /// and what permission levels they hold.
    ///
    /// Results are ordered by `user_id` ascending for deterministic output
    /// and capped at ``AppConstants/defaultPagination`` (1,000) records as a
    /// defensive guard (Rule 7 — Batch Memory Cap).
    ///
    /// - Parameter accountGroupId: The account group's unique identifier.
    /// - Returns: Array of entitlements for the account group, ordered by user ID.
    ///            Returns empty array if no users have entitlements for this group.
    public func findByAccountGroupId(_ accountGroupId: UInt64) async throws -> [Entitlement] {
        let logger = self.logger
        let limit = AppConstants.defaultPagination
        return try await pool.withConnection { db in
            logger.info("Finding entitlements for accountGroupId: \(accountGroupId) (limit \(limit))")
            let rows = try await db.query(
                "SELECT id, user_id, account_group_id, can_read, can_create, can_modify, can_delete FROM entitlements WHERE account_group_id = ? ORDER BY user_id ASC LIMIT ?",
                [MySQLData(int: Int(accountGroupId)), MySQLData(int: limit)]
            ).get()
            logger.info("Found \(rows.count) entitlement(s) for accountGroupId: \(accountGroupId)")
            return try rows.map { try EntitlementRepository.mapRow($0) }
        }
    }

    /// Updates the permission flags for an existing entitlement.
    ///
    /// Used by AdminView when modifying user-group entitlement assignments.
    /// Only the four permission flags (READ/CREATE/MODIFY/DELETE) are updated;
    /// the `user_id` and `account_group_id` columns are not modified.
    ///
    /// If no entitlement exists with the given ID, the UPDATE is a no-op
    /// (MySQL UPDATE WHERE with no matching rows).
    ///
    /// - Parameters:
    ///   - id: The entitlement's unique identifier.
    ///   - canRead: New READ permission flag value.
    ///   - canCreate: New CREATE permission flag value.
    ///   - canModify: New MODIFY permission flag value.
    ///   - canDelete: New DELETE permission flag value.
    public func updatePermissions(
        id: UInt64,
        canRead: Bool,
        canCreate: Bool,
        canModify: Bool,
        canDelete: Bool
    ) async throws {
        let logger = self.logger
        try await pool.withConnection { db in
            logger.info("Updating permissions for entitlement id: \(id) — read=\(canRead), create=\(canCreate), modify=\(canModify), delete=\(canDelete)")
            _ = try await db.query(
                "UPDATE entitlements SET can_read = ?, can_create = ?, can_modify = ?, can_delete = ? WHERE id = ?",
                [
                    MySQLData(bool: canRead),
                    MySQLData(bool: canCreate),
                    MySQLData(bool: canModify),
                    MySQLData(bool: canDelete),
                    MySQLData(int: Int(id))
                ]
            ).get()
            logger.info("Updated permissions for entitlement id: \(id)")
        }
    }

    /// Deletes an entitlement by user ID and account group ID combination.
    ///
    /// Revokes all permissions for a specific user-group pair. Used for complete
    /// entitlement removal when a user should lose all access to a particular
    /// account group.
    ///
    /// If no entitlement exists for the given user-group pair, the DELETE is a
    /// no-op (MySQL DELETE WHERE with no matching rows).
    ///
    /// - Parameters:
    ///   - userId: The user's unique identifier.
    ///   - accountGroupId: The account group's unique identifier.
    public func deleteByUserAndGroup(userId: UInt64, accountGroupId: UInt64) async throws {
        let logger = self.logger
        try await pool.withConnection { db in
            logger.info("Deleting entitlement for userId: \(userId), accountGroupId: \(accountGroupId)")
            _ = try await db.query(
                "DELETE FROM entitlements WHERE user_id = ? AND account_group_id = ?",
                [MySQLData(int: Int(userId)), MySQLData(int: Int(accountGroupId))]
            ).get()
            logger.info("Deleted entitlement for userId: \(userId), accountGroupId: \(accountGroupId)")
        }
    }

    // MARK: - Private Helpers

    /// Maps a MySQL result row to an `Entitlement` model.
    ///
    /// Extracts `id` (BIGINT UNSIGNED), `user_id` (BIGINT UNSIGNED),
    /// `account_group_id` (BIGINT UNSIGNED), and four permission flags
    /// (BOOLEAN / TINYINT(1)) from the result row.
    ///
    /// The `created_at` column present in the MySQL table is intentionally
    /// omitted as it is a database-level audit field not represented in the
    /// `Entitlement` model struct.
    ///
    /// This method is `static` to allow safe invocation from `@Sendable`
    /// closures passed to the connection pool without capturing `self`.
    ///
    /// - Parameter row: The MySQL result row containing the expected columns.
    /// - Returns: The mapped `Entitlement` instance.
    /// - Throws: `AppError.dataAccessFailed` if required columns are missing
    ///           or cannot be decoded to the expected types.
    private static func mapRow(_ row: MySQLRow) throws -> Entitlement {
        guard let id = row.column("id")?.uint64,
              let userId = row.column("user_id")?.uint64,
              let accountGroupId = row.column("account_group_id")?.uint64,
              let canRead = row.column("can_read")?.bool,
              let canCreate = row.column("can_create")?.bool,
              let canModify = row.column("can_modify")?.bool,
              let canDelete = row.column("can_delete")?.bool else {
            throw AppError.dataAccessFailed("Failed to map entitlement row: missing or invalid columns (id, user_id, account_group_id, can_read, can_create, can_modify, can_delete)")
        }
        return Entitlement(
            id: id,
            userId: userId,
            accountGroupId: accountGroupId,
            canRead: canRead,
            canCreate: canCreate,
            canModify: canModify,
            canDelete: canDelete
        )
    }
}
