// Sources/Persistence/Repositories/UserRepository.swift
// WealthLedger — User Repository for MySQL users Table
//
// Provides CRUD operations for the users table, including username-based lookup
// for authentication, duplicate username rejection via MySQL UNIQUE constraint
// handling, and paginated listing of users.
//
// Rule 8: MySQLKit-only persistence — NO SwiftData.
// Rule 7: Batch memory cap — findAll pagination capped at 1,000.
// Rule 10: Schema referential integrity — users table has typed PK, UNIQUE username.

import Foundation
import MySQLKit
import MySQLNIO
import SQLKit
import NIOCore
import Logging
import Shared

// MARK: - User Model

/// Represents an application user in the WealthLedger system.
///
/// Maps directly to the MySQL `users` table (001_create_users.sql).
/// This struct is defined in the Persistence module to enable `UserRepository`
/// to implement `RepositoryProtocol` with concrete type binding, since the
/// Persistence module cannot import RBAC (which would create a circular
/// dependency: RBAC → Persistence → RBAC).
///
/// ## Column Mapping
/// - `id`           → `BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY`
/// - `username`     → `VARCHAR(255) UNIQUE NOT NULL`
/// - `passwordHash` → `password_hash VARCHAR(255) NOT NULL`
///
/// ## Security
/// The `passwordHash` property stores ONLY the bcrypt hash output.
/// Plaintext passwords must NEVER be stored in this struct.
public struct User: Sendable, Equatable, Hashable, Codable {

    /// Unique user identifier, auto-generated by MySQL via AUTO_INCREMENT.
    /// Defaults to 0 for new users not yet persisted.
    public let id: UInt64

    /// Unique username used for authentication.
    public let username: String

    /// bcrypt-hashed password string (hashing performed by PasswordHasher in RBAC module).
    public let passwordHash: String

    /// Creates a new User instance.
    ///
    /// - Parameters:
    ///   - id: The unique user identifier. Defaults to 0 for new users before persistence.
    ///   - username: The unique username for authentication.
    ///   - passwordHash: The bcrypt-hashed password string.
    public init(id: UInt64 = 0, username: String, passwordHash: String) {
        self.id = id
        self.username = username
        self.passwordHash = passwordHash
    }
}

// MARK: - UserRepository

/// Repository for the `users` table providing complete CRUD operations,
/// username-based lookup for authentication, and duplicate username rejection.
///
/// Conforms to `RepositoryProtocol` with `User` as Entity and `UInt64` as EntityID.
///
/// ## Thread Safety (Gate 2 — Swift 6 Strict Concurrency)
/// All stored properties are immutable (`let`). `ConnectionPool` is an actor
/// (inherently `Sendable`). `Logger` from swift-log is `Sendable`. The class is
/// declared as `final class ... Sendable` without `@unchecked` since all invariants
/// are satisfied by construction.
///
/// ## Rule 8 — MySQLKit-Only Persistence
/// All database operations use MySQLKit/MySQLNIO exclusively. No SwiftData.
///
/// ## Rule 7 — Batch Memory Cap
/// `findAll` enforces a maximum page size of `AppConstants.defaultPagination` (1,000).
///
/// ## Rule 10 — Schema Referential Integrity
/// The `users` table has a `BIGINT UNSIGNED AUTO_INCREMENT` primary key and a
/// `UNIQUE` constraint on `username`. The `entitlements` table references `users`
/// via foreign key; deleting a user may fail with an FK constraint error if
/// entitlements still reference the user.
public final class UserRepository: RepositoryProtocol, Sendable {

    public typealias Entity = User
    public typealias EntityID = UInt64

    /// AsyncKit-based MySQL connection pool injected via dependency injection.
    private let pool: ConnectionPool

    /// Structured logger for repository operations.
    private let logger: Logger

    /// Creates a new UserRepository with the given connection pool.
    ///
    /// - Parameters:
    ///   - pool: The connection pool for database operations.
    ///   - logger: Structured logger. Defaults to label "persistence.user-repository".
    public init(
        pool: ConnectionPool,
        logger: Logger = Logger(label: "persistence.user-repository")
    ) {
        self.pool = pool
        self.logger = logger
    }

    // MARK: - RepositoryProtocol Conformance

    /// Retrieves a user by primary key.
    ///
    /// - Parameter id: The user's unique identifier (BIGINT UNSIGNED).
    /// - Returns: The matching `User`, or `nil` if no user exists with that ID.
    public func findById(_ id: UInt64) async throws -> User? {
        let logger = self.logger
        return try await pool.withConnection { db in
            logger.info("Finding user by id: \(id)")
            let rows = try await db.query(
                "SELECT id, username, password_hash FROM users WHERE id = ?",
                [MySQLData(int: Int(id))]
            ).get()
            guard let row = rows.first else {
                return nil
            }
            return try UserRepository.mapRow(row)
        }
    }

    /// Retrieves a paginated list of users ordered by ID ascending.
    ///
    /// Enforces Rule 7: page size is capped at `AppConstants.defaultPagination` (1,000).
    /// Pages are 1-based; page values less than 1 are clamped to 1.
    ///
    /// - Parameters:
    ///   - page: 1-based page number. Values < 1 are clamped to 1.
    ///   - pageSize: Maximum records per page. Values > 1,000 are clamped to 1,000.
    ///              Values < 1 are clamped to 1.
    /// - Returns: Array of users for the requested page, may be empty.
    public func findAll(page: Int, pageSize: Int) async throws -> [User] {
        let effectivePageSize = min(max(pageSize, 1), AppConstants.defaultPagination)
        let effectivePage = max(page, 1)
        let offset = (effectivePage - 1) * effectivePageSize
        let logger = self.logger

        return try await pool.withConnection { db in
            logger.info("Finding all users: page=\(effectivePage), pageSize=\(effectivePageSize), offset=\(offset)")
            let rows = try await db.query(
                "SELECT id, username, password_hash FROM users ORDER BY id ASC LIMIT ? OFFSET ?",
                [MySQLData(int: effectivePageSize), MySQLData(int: offset)]
            ).get()
            return try rows.map { try UserRepository.mapRow($0) }
        }
    }

    /// Creates a new user in the database.
    ///
    /// Inserts a row into the `users` table with the provided username and
    /// password hash. The auto-generated ID is retrieved via `LAST_INSERT_ID()`
    /// on the same connection to guarantee correctness.
    ///
    /// ## Duplicate Username Handling
    /// If the `username` already exists (UNIQUE constraint violation), MySQL
    /// returns error code 1062 (ER_DUP_ENTRY), which MySQLNIO maps to
    /// `MySQLError.duplicateEntry`. This is caught and re-thrown as
    /// `AppError.duplicateUser` for application-layer handling.
    ///
    /// - Parameter entity: The user to create. The `id` field is ignored;
    ///                     MySQL generates the auto-increment ID.
    /// - Returns: The created user with the auto-generated ID populated.
    /// - Throws: `AppError.duplicateUser` if the username already exists.
    public func create(_ entity: User) async throws -> User {
        let username = entity.username
        let passwordHash = entity.passwordHash
        let logger = self.logger

        do {
            return try await pool.withConnection { db in
                logger.info("Creating user with username: \(username)")

                _ = try await db.query(
                    "INSERT INTO users (username, password_hash) VALUES (?, ?)",
                    [MySQLData(string: username), MySQLData(string: passwordHash)]
                ).get()

                // Retrieve the auto-generated ID on the same connection
                let idRows = try await db.query(
                    "SELECT LAST_INSERT_ID() AS insert_id"
                ).get()
                guard let insertId = idRows.first?.column("insert_id")?.uint64 else {
                    logger.error("Failed to retrieve LAST_INSERT_ID after user creation for username: \(username)")
                    throw AppError.dataAccessFailed("LAST_INSERT_ID returned nil after user creation for username: \(username)")
                }

                logger.info("Created user '\(username)' with id: \(insertId)")
                return User(id: insertId, username: username, passwordHash: passwordHash)
            }
        } catch let appError as AppError {
            // Re-throw application errors (including dataAccessFailed from LAST_INSERT_ID failure)
            throw appError
        } catch let mysqlError as MySQLError {
            // Handle MySQL duplicate entry error (error code 1062 / ER_DUP_ENTRY)
            if case .duplicateEntry = mysqlError {
                logger.error("Duplicate username rejected: \(username)")
                throw AppError.duplicateUser
            }
            logger.error("MySQL error during user creation: \(mysqlError)")
            throw mysqlError
        }
    }

    /// Deletes a user by primary key.
    ///
    /// - Parameter id: The user's unique identifier.
    /// - Note: This operation may fail with a foreign key constraint error if
    ///         the `entitlements` table still references this user. Callers
    ///         should remove associated entitlements before deleting the user.
    public func delete(_ id: UInt64) async throws {
        let logger = self.logger
        try await pool.withConnection { db in
            logger.info("Deleting user with id: \(id)")
            _ = try await db.query(
                "DELETE FROM users WHERE id = ?",
                [MySQLData(int: Int(id))]
            ).get()
            logger.info("Deleted user with id: \(id)")
        }
    }

    // MARK: - Domain-Specific Methods

    /// Finds a user by username — the primary authentication lookup method.
    ///
    /// This is the sole lookup path used by `AuthenticationService.login()`
    /// to retrieve the user record and bcrypt password hash for verification.
    ///
    /// - Parameter username: The username to search for (case-sensitive match
    ///                       against the `username` column).
    /// - Returns: The matching `User` including the `passwordHash` field, or
    ///            `nil` if no user exists with that username.
    public func findByUsername(_ username: String) async throws -> User? {
        let logger = self.logger
        return try await pool.withConnection { db in
            logger.info("Finding user by username: \(username)")
            let rows = try await db.query(
                "SELECT id, username, password_hash FROM users WHERE username = ?",
                [MySQLData(string: username)]
            ).get()
            guard let row = rows.first else {
                return nil
            }
            return try UserRepository.mapRow(row)
        }
    }

    /// Checks whether a username already exists in the database.
    ///
    /// Provides a pre-creation uniqueness check as an alternative to catching
    /// duplicate key errors from `create(_:)`. Useful when the caller wants
    /// to provide early feedback before attempting the INSERT.
    ///
    /// - Parameter username: The username to check.
    /// - Returns: `true` if the username exists, `false` otherwise.
    public func existsByUsername(_ username: String) async throws -> Bool {
        let logger = self.logger
        return try await pool.withConnection { db in
            logger.info("Checking existence of username: \(username)")
            let rows = try await db.query(
                "SELECT COUNT(*) AS cnt FROM users WHERE username = ?",
                [MySQLData(string: username)]
            ).get()
            guard let countData = rows.first?.column("cnt") else {
                return false
            }
            // MySQL COUNT returns BIGINT; handle both Int and UInt64 decoding paths
            if let intCount = countData.int {
                return intCount > 0
            }
            if let uint64Count = countData.uint64 {
                return uint64Count > 0
            }
            return false
        }
    }

    /// Updates an existing user's username and password hash.
    ///
    /// Used for password changes and username modifications. The user is
    /// identified by `entity.id`; both `username` and `passwordHash`
    /// columns are updated.
    ///
    /// - Parameter entity: The user with updated values. The `id` must
    ///                     correspond to an existing user row.
    /// - Returns: The updated user entity (echoed back with the same values).
    public func update(_ entity: User) async throws -> User {
        let entityId = entity.id
        let username = entity.username
        let passwordHash = entity.passwordHash
        let logger = self.logger

        try await pool.withConnection { db in
            logger.info("Updating user with id: \(entityId)")
            _ = try await db.query(
                "UPDATE users SET username = ?, password_hash = ? WHERE id = ?",
                [
                    MySQLData(string: username),
                    MySQLData(string: passwordHash),
                    MySQLData(int: Int(entityId))
                ]
            ).get()
            logger.info("Updated user with id: \(entityId)")
        }
        return entity
    }

    /// Returns the total number of users in the database.
    ///
    /// The system is designed for approximately 300 registered users.
    ///
    /// - Returns: Total user count as an `Int`.
    public func count() async throws -> Int {
        let logger = self.logger
        return try await pool.withConnection { db in
            logger.info("Counting total users")
            let rows = try await db.query("SELECT COUNT(*) AS cnt FROM users").get()
            guard let countData = rows.first?.column("cnt") else {
                return 0
            }
            // MySQL COUNT returns BIGINT; handle both Int and UInt64 decoding paths
            if let intCount = countData.int {
                return intCount
            }
            if let uint64Count = countData.uint64 {
                return Int(uint64Count)
            }
            return 0
        }
    }

    // MARK: - Private Helpers

    /// Maps a MySQL result row to a `User` model.
    ///
    /// Extracts `id` (BIGINT UNSIGNED), `username` (VARCHAR), and
    /// `password_hash` (VARCHAR) columns from the row. The `created_at`
    /// column is intentionally omitted as it is a database-level audit field
    /// not represented in the `User` model.
    ///
    /// This method is `static` to allow safe invocation from `@Sendable`
    /// closures passed to the connection pool without capturing `self`.
    ///
    /// - Parameter row: The MySQL result row containing the expected columns.
    /// - Returns: The mapped `User` instance.
    /// - Throws: `AppError.dataAccessFailed` if required columns are missing
    ///           or cannot be decoded to the expected types.
    private static func mapRow(_ row: MySQLRow) throws -> User {
        guard let id = row.column("id")?.uint64,
              let username = row.column("username")?.string,
              let passwordHash = row.column("password_hash")?.string else {
            throw AppError.dataAccessFailed("Failed to map user row: missing or invalid columns (id, username, password_hash)")
        }
        return User(id: id, username: username, passwordHash: passwordHash)
    }
}
