// Entitlement.swift
// WealthLedger - RBAC Module
//
// Defines the Entitlement data model representing per-user per-account-group
// permission flags (READ/CREATE/MODIFY/DELETE). Maps to the MySQL `entitlements`
// table (003_create_entitlements.sql). This is a core data structure for Rule 4
// (Entitlement Enforcement) and is consumed by EntitlementRepository,
// EntitlementService, AdminView, and EntitlementFormView.
//
// MySQL Column Mapping:
//   id              → id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
//   userId          → user_id BIGINT UNSIGNED NOT NULL  (FK → users.id)
//   accountGroupId  → account_group_id BIGINT UNSIGNED NOT NULL  (FK → account_groups.id)
//   canRead         → can_read BOOLEAN NOT NULL DEFAULT FALSE
//   canCreate       → can_create BOOLEAN NOT NULL DEFAULT FALSE
//   canModify       → can_modify BOOLEAN NOT NULL DEFAULT FALSE
//   canDelete       → can_delete BOOLEAN NOT NULL DEFAULT FALSE
//
// Rule 4 (Entitlement Enforcement): All data reads must verify user-group
// entitlement before returning records. Users without READ access to an account
// group receive an empty result set — not an error.
//
// Swift 6 Strict Concurrency: This struct achieves natural `Sendable` conformance
// through immutable value-type properties only. No `@unchecked Sendable` needed.

import Foundation

/// Represents a per-user per-account-group permission assignment in the
/// WealthLedger RBAC system.
///
/// `Entitlement` is a pure value type that maps directly to the MySQL
/// `entitlements` table. All properties are immutable (`let`) value types
/// (`UInt64`, `Bool`), providing natural `Sendable` conformance for Swift 6
/// strict concurrency without any `@unchecked` annotations.
///
/// Each entitlement record associates a user with an account group and specifies
/// four independent permission flags: READ, CREATE, MODIFY, and DELETE. These
/// flags are checked by `EntitlementService` before any data access operation
/// to enforce Rule 4 (Entitlement Enforcement).
///
/// ## Usage
/// ```swift
/// // Creating a new entitlement (before DB insertion, id defaults to 0)
/// let entitlement = Entitlement(
///     userId: 1,
///     accountGroupId: 10,
///     canRead: true,
///     canCreate: false,
///     canModify: false,
///     canDelete: false
/// )
///
/// // Entitlement retrieved from database (with assigned id)
/// let dbEntitlement = Entitlement(
///     id: 42,
///     userId: 1,
///     accountGroupId: 10,
///     canRead: true,
///     canCreate: true,
///     canModify: true,
///     canDelete: false
/// )
///
/// // Check a specific permission by name
/// let canRead = dbEntitlement.hasPermission("READ")  // true
/// let canDelete = dbEntitlement.hasPermission("DELETE")  // false
/// ```
///
/// ## Consumers
/// - `EntitlementRepository` — row mapping from MySQLRow, CRUD operations
/// - `EntitlementService` — permission checks, group filtering
/// - `AdminView` — entitlement assignment display
/// - `EntitlementFormView` — permission form binding
public struct Entitlement: Sendable, Equatable, Hashable, Codable {

    // MARK: - Properties

    /// Unique entitlement identifier, auto-generated by MySQL via AUTO_INCREMENT.
    ///
    /// Defaults to `0` for newly created `Entitlement` instances that have not yet
    /// been persisted to the database. The actual identifier is assigned by MySQL
    /// upon insertion and should be read back from the inserted row.
    ///
    /// Maps to: `id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY`
    public let id: UInt64

    /// Foreign key referencing the user who holds this entitlement.
    ///
    /// References the `users.id` column via the `fk_entitlements_user` foreign key
    /// constraint defined in the MySQL schema. Must correspond to an existing user
    /// record.
    ///
    /// Maps to: `user_id BIGINT UNSIGNED NOT NULL` (FK → `users.id`)
    public let userId: UInt64

    /// Foreign key referencing the account group this entitlement applies to.
    ///
    /// References the `account_groups.id` column via the
    /// `fk_entitlements_account_group` foreign key constraint defined in the MySQL
    /// schema. Must correspond to an existing account group record.
    ///
    /// Maps to: `account_group_id BIGINT UNSIGNED NOT NULL` (FK → `account_groups.id`)
    public let accountGroupId: UInt64

    /// READ permission flag for the associated account group.
    ///
    /// When `true`, the user is permitted to view accounts and related data within
    /// this account group. When `false`, all queries for this group return an empty
    /// result set for this user (Rule 4 — Entitlement Enforcement).
    ///
    /// Maps to: `can_read BOOLEAN NOT NULL DEFAULT FALSE`
    public let canRead: Bool

    /// CREATE permission flag for the associated account group.
    ///
    /// When `true`, the user is permitted to create new accounts, transactions,
    /// and other records within this account group.
    ///
    /// Maps to: `can_create BOOLEAN NOT NULL DEFAULT FALSE`
    public let canCreate: Bool

    /// MODIFY permission flag for the associated account group.
    ///
    /// When `true`, the user is permitted to update existing accounts and records
    /// within this account group (excluding transaction immutability per Rule 2).
    ///
    /// Maps to: `can_modify BOOLEAN NOT NULL DEFAULT FALSE`
    public let canModify: Bool

    /// DELETE permission flag for the associated account group.
    ///
    /// When `true`, the user is permitted to remove records (where allowed by
    /// business rules) within this account group.
    ///
    /// Maps to: `can_delete BOOLEAN NOT NULL DEFAULT FALSE`
    public let canDelete: Bool

    // MARK: - Initializer

    /// Creates a new `Entitlement` instance.
    ///
    /// - Parameters:
    ///   - id: The unique entitlement identifier. Defaults to `0` for new
    ///         entitlements that have not yet been persisted (MySQL assigns the
    ///         actual ID via AUTO_INCREMENT on insert).
    ///   - userId: The foreign key referencing the user who holds this entitlement.
    ///             Must correspond to an existing user record.
    ///   - accountGroupId: The foreign key referencing the account group this
    ///                     entitlement applies to. Must correspond to an existing
    ///                     account group record.
    ///   - canRead: READ permission flag. When `false`, queries for this group
    ///              return empty results for this user (Rule 4).
    ///   - canCreate: CREATE permission flag for the associated account group.
    ///   - canModify: MODIFY permission flag for the associated account group.
    ///   - canDelete: DELETE permission flag for the associated account group.
    public init(
        id: UInt64 = 0,
        userId: UInt64,
        accountGroupId: UInt64,
        canRead: Bool,
        canCreate: Bool,
        canModify: Bool,
        canDelete: Bool
    ) {
        self.id = id
        self.userId = userId
        self.accountGroupId = accountGroupId
        self.canRead = canRead
        self.canCreate = canCreate
        self.canModify = canModify
        self.canDelete = canDelete
    }

    // MARK: - Convenience Methods

    /// Checks whether this entitlement grants a specific permission by name.
    ///
    /// Maps human-readable permission strings to the corresponding boolean
    /// permission flag. The comparison is case-insensitive to support flexible
    /// usage from service layers and UI components.
    ///
    /// This method is used by `EntitlementService.checkPermission(userId:
    /// accountGroupId:permission:)` to efficiently evaluate a specific permission
    /// by name against the entitlement record.
    ///
    /// - Parameter permission: The permission name to check. Recognized values
    ///   are `"READ"`, `"CREATE"`, `"MODIFY"`, and `"DELETE"` (case-insensitive).
    /// - Returns: `true` if the permission is granted, `false` if the permission
    ///   is denied or the permission name is not recognized.
    ///
    /// ## Examples
    /// ```swift
    /// let entitlement = Entitlement(
    ///     userId: 1,
    ///     accountGroupId: 10,
    ///     canRead: true,
    ///     canCreate: false,
    ///     canModify: true,
    ///     canDelete: false
    /// )
    ///
    /// entitlement.hasPermission("READ")    // true
    /// entitlement.hasPermission("read")    // true (case-insensitive)
    /// entitlement.hasPermission("CREATE")  // false
    /// entitlement.hasPermission("MODIFY")  // true
    /// entitlement.hasPermission("DELETE")  // false
    /// entitlement.hasPermission("ADMIN")   // false (unknown permission)
    /// ```
    public func hasPermission(_ permission: String) -> Bool {
        switch permission.uppercased() {
        case "READ":
            return canRead
        case "CREATE":
            return canCreate
        case "MODIFY":
            return canModify
        case "DELETE":
            return canDelete
        default:
            return false
        }
    }
}
