// User.swift
// WealthLedger - RBAC Module
//
// Defines the User data model representing an application user with bcrypt-hashed
// password storage. Maps to the MySQL `users` table (001_create_users.sql).
//
// MySQL Column Mapping:
//   id            → id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
//   username      → username VARCHAR(255) UNIQUE NOT NULL
//   passwordHash  → password_hash VARCHAR(255) NOT NULL
//
// Security: The `passwordHash` property stores ONLY the bcrypt hash output
// (e.g., "$2b$12$..."). Plaintext passwords must NEVER be stored in this struct.
// Hashing is performed by `PasswordHasher`; storage/retrieval by `UserRepository`.
//
// Swift 6 Strict Concurrency: This struct achieves natural `Sendable` conformance
// through immutable value-type properties only. No `@unchecked Sendable` needed.

import Foundation

/// Represents an application user in the WealthLedger RBAC system.
///
/// `User` is a pure value type that maps directly to the MySQL `users` table.
/// All properties are immutable (`let`) value types (`UInt64`, `String`), providing
/// natural `Sendable` conformance for Swift 6 strict concurrency without any
/// `@unchecked` annotations.
///
/// ## Usage
/// ```swift
/// // Creating a new user (before DB insertion, id defaults to 0)
/// let newUser = User(username: "admin", passwordHash: hashedPassword)
///
/// // User retrieved from database (with assigned id)
/// let dbUser = User(id: 42, username: "admin", passwordHash: "$2b$12$...")
/// ```
///
/// ## Consumers
/// - `UserRepository` — row mapping from MySQLRow, CRUD operations
/// - `AuthenticationService` — login verification, user creation flow
/// - `AdminView` — user creation form display
/// - `AppState` — current user session tracking
public struct User: Sendable, Equatable, Hashable, Codable {

    // MARK: - Properties

    /// Unique user identifier, auto-generated by MySQL via AUTO_INCREMENT.
    ///
    /// Defaults to `0` for newly created `User` instances that have not yet been
    /// persisted to the database. The actual identifier is assigned by MySQL upon
    /// insertion and should be read back from the inserted row.
    ///
    /// Maps to: `id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY`
    public let id: UInt64

    /// Unique username used for authentication.
    ///
    /// Enforced as unique at the database level via a `UNIQUE` constraint on the
    /// `username` column. Must be non-empty and is used as the primary login
    /// credential alongside the password.
    ///
    /// Maps to: `username VARCHAR(255) UNIQUE NOT NULL`
    public let username: String

    /// bcrypt-hashed password string.
    ///
    /// Stores the OUTPUT of bcrypt hashing (performed by `PasswordHasher`).
    /// The typical bcrypt output format is `$2b$12$...` (60 characters), which
    /// fits within the `VARCHAR(255)` column constraint.
    ///
    /// **Security**: Plaintext passwords must NEVER be assigned to this property.
    /// Always use `PasswordHasher.hash(_:)` to produce the hash before creating
    /// a `User` instance.
    ///
    /// Maps to: `password_hash VARCHAR(255) NOT NULL`
    public let passwordHash: String

    // MARK: - Initializer

    /// Creates a new `User` instance.
    ///
    /// - Parameters:
    ///   - id: The unique user identifier. Defaults to `0` for new users that
    ///         have not yet been persisted (MySQL assigns the actual ID via
    ///         AUTO_INCREMENT on insert).
    ///   - username: The unique username for authentication. Must be non-empty
    ///               and unique across all users in the system.
    ///   - passwordHash: The bcrypt-hashed password string. Must be the output
    ///                   of `PasswordHasher.hash(_:)` — never a plaintext password.
    public init(
        id: UInt64 = 0,
        username: String,
        passwordHash: String
    ) {
        self.id = id
        self.username = username
        self.passwordHash = passwordHash
    }
}
